const ShopActionTypes = {
  FETCH_COLLECITONS_START: 'FETCH_COLLECITONS_START',
  FETCH_COLLECITONS_SUCCESS: 'FETCH_COLLECITONS_SUCCESS',
  FETCH_COLLECITONS_FAILURE: 'FETCH_COLLECITONS_FAILURE'
};

export default ShopActionTypes;
